### ISSUE TITLE
Overide CSS

### ISSUE THREAD

**Issue by udayreddym** [dbilgili/Custom-ReactJS-Dropdown-Components#2]
Can you help me to override css?

**Comment by dbilgili** [comment]
If you have already tried to use your own styles with the class names used in [this](https://github.com/dbilgili/Custom-ReactJS-Dropdown-Components/blob/master/src/styles/stylus/dropdown.styl) styling file, you might not be overriding them. Try using `!important` next to your custom styling rules.

For instance, the following example should result in `2px` thick red border.
```css
.dd-wrapper .dd-header {
  border: 2px solid red !important;
}
````
